default:
  image: maven


test:
  stage: test
  script: cd get-fit && mvn test
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"


test-coverage:
  stage: test
  script: cd get-fit && mvn verify
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
