default:
  image: maven

stages:
  - build
  - test
  - coverage
  - quality
  - bugs

validate:
  stage: build
  script: cd get-fit && mvn validate
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

compile:
  stage: build
  needs: ["validate"]
  script: cd get-fit && mvn compile
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"
  artifacts:
    paths:
      - get-fit/core/target/classes/*
      - get-fit/localpersistence/target/classes/*
      - get-fit/ui/target/classes/*
    expire_in: 10 minutes

test:
  stage: test
  needs: ["compile"]
  script: cd get-fit && mvn test
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


test-coverage-minimum:
  stage: coverage
  needs: ["compile"]
  script: cd get-fit && mvn verify
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

test-coverage-80:
  stage: coverage
  needs: ["test-coverage-minimum"]
  script: cd get-fit && mvn verify -Dminimum=0.8
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


checkstyle:
  stage: quality
  needs: ["compile"]
  script: cd get-fit && mvn checkstyle:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

spotbugs:
  stage: bugs
  needs: ["compile"]
  script: cd get-fit && mvn install && mvn spotbugs:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"