default:
  image: maven

test:
  stage: test
  script: cd get-fit && mvn test
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - when: never

test-coverage:
  stage: test
  script: cd get-fit && mvn verify
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - when: never