default:
  image: maven

stages:
  - test
  - build
  - minimum-coverage
  - extended-coverage
  - code-quality
  - bugs

test:
  stage: test
  script: cd get-fit && mvn test
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

compile:
  stage: build
  script: cd get-fit && mvn compile
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

install:
  stage: build
  script: cd get-fit && mvn install
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"



test-coverage-minimum:
  stage: minimum-coverage
  script: cd get-fit && mvn verify
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

test-coverage-80:
  stage: extended-coverage
  script: cd get-fit && mvn verify -Dminimum=0.8
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


checkstyle:
  stage: code-quality
  script: cd get-fit && mvn checkstyle:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

spotbugs:
  stage: bugs
  script: cd get-fit && mvn install && mvn spotbugs:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"