default:
  image: maven

stages:
  - build
  - test
  - coverage
  - quality
  - bugs
  - distribute

validate:
  stage: build
  script: cd get-fit && mvn validate
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

compile:
  stage: build
  script: cd get-fit && mvn compile
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"
  artifacts:
    paths:
      - get-fit/core/target/classes/*
      - get-fit/localpersistence/target/classes/*
      - get-fit/ui/target/classes/*
    expire_in: 10 minutes

test:
  stage: test
  needs: ["compile"]
  script: cd get-fit && mvn test -DnoTestUI=true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"
  artifacts:
    paths:
      - get-fit/core/target/surefire-reports/*.xml
      - get-fit/localpersistance/target/surefire-reports/*.xml
      - get-fit/ui/target/surefire-reports/*.xml
    reports:
      junit:
      - get-fit/core/target/surefire-reports/*.xml
      - get-fit/core/target/surefire-reports/*.xml
      - get-fit/core/target/surefire-reports/*.xml



test-coverage-minimum:
  stage: coverage
  needs: ["compile"]
  script: cd get-fit && mvn verify -DnoTestUI=true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

test-coverage-80:
  stage: coverage
  needs: ["compile"]
  script: cd get-fit && mvn verify -Dminimum=0.8 -DnoTestUI=true
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


checkstyle:
  stage: quality
  needs: ["compile"]
  script: cd get-fit && mvn checkstyle:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

spotbugs:
  stage: bugs
  needs: ["compile"]
  script: cd get-fit && mvn install -DnoTestUI=true && mvn spotbugs:check -DnoTestUI=true
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

distribute:
  stage: distribute
  script: cd get-fit && mvn install -DnoTestUI=true && cd ui && mvn compile javafx:jlink jpackage:jpackage
  allow_failure: false
  rules:
    if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  artifacts:
    paths:
      - get-fit/ui/target/dist/*