default:
  image: maven

stages:
  - test
  - minimum-coverage
  - coverage
  - quality

test:
  stage: test
  script: cd get-fit && mvn test
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


test-coverage-minimum:
  stage: minimum-coverage
  script: cd get-fit && mvn verify
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"

test-coverage-80:
  stage: coverage
  script: cd get-fit && mvn verify -Dminimum=0.8
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"


checkstyle:
  stage: quality
  script: cd get-fit && mvn checkstyle:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"