@startuml Get Fit Architecture
allowmixing
component core {
    package core.core
}

component localpersistence {
    package localpersistence.localpersistence
}

component ui {
    package ui.ui
}

component javafx {
    package javafx.controls
    package javafx.fxml
}

component json {
    package json.simple
}

ui.ui ..> core.core
ui.ui ..> localpersistence.localpersistence
ui.ui ..> javafx.controls
ui.ui ..> javafx.fxml

localpersistence.localpersistence ..> core.core
localpersistence.localpersistence ..> json.simple


@enduml
